name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: export PATH="./toolchain/cross/bin:$PATH"
    - name: make
      run: fs_scripts/fs_setup.sh
    - name: make check
      run: make
    - name: make distcheck
      run: ./fs.sh
